name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: '${{ github.workspace }}/go.mod'

    - name: Get dependencies
      run: |
        # Download GeoIP test data from MaxMind
        git submodule update --init

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -benchmem -bench=. ./... -benchtime=100ms
